#!/usr/bin/env node
// Converts a CSV of emails into lib/emails.ts.
// Usage: node scripts/csv-to-ts.mjs path/to/your.csv
//
// Expects 4 columns in fixed positional order (header row optional):
//   col 0 = Company
//   col 1 = Full Name
//   col 2 = Email
//   col 3 = First Name
//
// Rows where col 2 is not a valid email are skipped (so a header row, if
// present, is automatically ignored).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { parse } from 'csv-parse/sync';

const input = process.argv[2];
if (!input) {
  console.error('Usage: node scripts/csv-to-ts.mjs path/to/your.csv');
  process.exit(1);
}

const csvText = readFileSync(resolve(input), 'utf-8');
const records = parse(csvText, {
  columns: false,
  skip_empty_lines: true,
  trim: true,
  bom: true,
  relax_column_count: true,
});

function looksLikeEmail(s) {
  return typeof s === 'string' && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
}

const parsed = records.map((cols) => ({
  company: String(cols[0] ?? '').trim(),
  fullName: String(cols[1] ?? '').trim(),
  email: String(cols[2] ?? '').trim(),
  firstName: String(cols[3] ?? '').trim(),
}));

const totalRows = parsed.length;
const valid = parsed.filter((r) => looksLikeEmail(r.email));
const skipped = totalRows - valid.length;

const seen = new Set();
const deduped = valid.filter((r) => {
  const key = r.email.toLowerCase();
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});
const droppedDupes = valid.length - deduped.length;

const output = `// AUTO-GENERATED by scripts/csv-to-ts.mjs. Do not edit by hand.
// Regenerate: node scripts/csv-to-ts.mjs path/to/your.csv

export interface EmailRow {
  company: string;
  fullName: string;
  email: string;
  firstName: string;
}

export const EMAILS: EmailRow[] = ${JSON.stringify(deduped, null, 2)};
`;

const outPath = resolve('lib/emails.ts');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, output);

console.log(`Wrote ${outPath}`);
console.log(`  ${deduped.length} rows`);
if (skipped > 0) console.log(`  ${skipped} skipped (no valid email — includes header row if present)`);
if (droppedDupes > 0) console.log(`  ${droppedDupes} dropped (duplicate emails)`);
